import React from "react";
import { Box, Typography } from "@mui/material";

const TermsOfUse: React.FC = () => {
  return (
    <Box sx={{
      padding: "10vh",
      "@media (max-width: 768px)": {
        padding: "5vh 2vh",
      }
    }}>
      <Typography variant="h4" sx={{ color: "white", textAlign: "center" }}>
        Terms of Use
      </Typography>
      <Typography
        variant="h6"
        sx={{ color: "white", textAlign: "justify", padding: "2vw 5vw" }}
        paragraph
      >
        1. Acceptance of Terms: By accessing and using the Folklof Platform, you
        agree to abide by these Terms of Use. If you do not agree with any part
        of these terms, please refrain from using our platform.
        <Typography variant="h6" sx={{ mb: 4, mt: 4 }}>
          2. User Accounts: You are responsible for maintaining the
          confidentiality of your account credentials. Any activities under your
          account are your responsibility.
        </Typography>
        3. Content Usage: The stories generated by AI on this platform are for
        educational purposes. Unauthorized reproduction or distribution of
        content is strictly prohibited.
        <Typography variant="h6" sx={{ mb: 4, mt: 4 }}>
          4. Parental Controls: Parents or guardians are advised to use the
          parental control features to monitor and manage their child's usage of
          the platform.
        </Typography>
        5. Limitation of Liability: We are not liable for any direct, indirect,
        or consequential loss or damage arising from the use of our platform.
        <Typography variant="h6" sx={{ mb: 4, mt: 4 }}>
          6. Changes to Terms: Folklof reserves the right to modify these terms
          at any time. Users will be notified of significant changes.
        </Typography>
        7. Termination: We reserve the right to terminate user accounts for
        violations of these terms or any inappropriate use of the platform.
      </Typography>
    </Box>
  );
};

export default TermsOfUse;
